### ISSUE TITLE
Change name of repo/solution from “container queries” to “element queries”?

### ISSUE THREAD

**Issue by ZeeCoder** [WICG/container-queries#8]
I would like us to start the discussion this year by deciding on a "name" everyone could get behind.

Now I know that even the repo is called **"container-queries"**, but I think there are some people out there that would rather call it **"element query"**, or something else altogether.

**Why is this important?**
We need to be on the same page on this from the beginning, otherwise when it comes to talking about the exact syntax, I can already see ourselves get sidetracked by the fact that someone used "container" while another example has "element" and a third some version of "media".

In my opinion this could lead to discussions that are ultimately pointless, very much like the semicolon vs  no semicolon in javascript.

Let's just pick a name, and stick with it.
That will also make syntax examples more consistent.

**Now, My Opinion**

I would **keep the "container"** name. 😂

I saw some people proposing syntaxes with "media", but I think we should make it obvious from the very beginning that this is something different from media queries to avoid confusion.

Historically to me it seems that we first started with "element" query, which was only about changing an element's styling based on some conditions on that very element.

Then, "container" queries started to pop up, which could also affect child elements inside the main "containing" element, hence the naming.

Example on how different the two might feel with a made-up syntax:
```css
@element .SomeClass (width > 200px) {
  /* Only rules are allowed here */
  font-size: 16px;
}
```

```css
@container .SomeClass (width > 200px) {
  :self {
    font-size: 14px;
  }

  .Child {
    font-size: 16px;
  }
}
```

In the case of the latter, instances of the ".SomeClass" element individually influence child nodes' styles, based on their own conditions.
(They are scoped in this sense.)

From experience, I think the latter is way more powerful than only applying styles to the element itself.

Now all that being said, I'm not totally against calling it `@element` query either, so long as the same concept of containment / scoping applies.
